### ISSUE TITLE
`agc workflow run` always zips everything

### ISSUE THREAD

**Issue by multimeric** [aws/amazon-genomics-cli#212]
[//]: #  (Please do not include your AWS account or credentials as part of the bug request.)

**Describe the Bug**

`agc workflow run` will zip whatever is at the `sourceURL` of the workflow in question, even if it is:

* A single file ie `main.nf`
* Already a zip file, ie `bundle.zip`, which contradicts the documentation

**Steps to Reproduce**

* Have the following `agc-project.yml`:
```
name: SomeWorkflows
schemaVersion: 1
workflows:
  somePipe:
    type:
      language: nextflow
      version: 1.0
    sourceURL: bundle.zip
contexts:
  SomeContext:
    instanceTypes:
      - "c6g.medium"
    engines:
      - type: nextflow
        engine: nextflow
```
* 
    ```bash 
    agc workflow run somePipe --context SomeContext
    ```
* Grab the S3 URL of the archive from the AWS Batch console Job page
* Download the file from S3
* Unzip it
* You will notice that inside `workflow.zip` is `bundle.zip`, which is not correct behaviour

**Relevant Logs**

n/a

**Expected Behavior**

`workflow.zip` should *be* `bundle.zip`, not contain it. So for example `main.nf` should be a file in both.

**Actual Behavior**

`workflow.zip` contains `bundle.zip`

**Screenshots**

n/a

**Additional Context**

[//]: #  (Add any other context about the problem here. The minimum required information is below)

Operating System:
AGC Version: 1.1.2
Was AGC setup with a custom bucket: No
Was AGC setup with a custom VPC: No
