### ISSUE TITLE
consolidate gatk-best-practices projects

### ISSUE THREAD

**Issue by wleepang** [aws/amazon-genomics-cli#349]
[//]: #  (Before raising the feature request, please check to see if an existing feature request already exists.)

**Description**

[//]: #  (A short description of the feature you are proposing.)
The only difference between the two `gatk-best-practices*` example projects is the engine used in contexts specified in `agc-project.yaml`

**Use Case**

[//]: #  (Why do you need this feature?)
Reduce the number of example projects and example workflows that need to be maintained.

**Proposed Solution**

[//]: #  (Please include prototype/workaround/sketch/reference implementation.)
Remove the `gatk-best-practices-project-miniwdl` project.

Modify the contexts defined in `agc-project.yaml` in `gatk-best-practices-project` to be:

```
contexts:
  # The on demand context uses on-demand EC2 instances which may be more expensive but will not be interrupted
  onDemandCtxCromwell:
    requestSpotInstances: false
    engines:
      - type: wdl
        engine: cromwell

  # The spot context uses EC2 spot instances which are usually cheaper but may be interrupted
  spotCtxCromwell:
    requestSpotInstances: true
    engines:
      - type: wdl
        engine: cromwell

  # The on demand context uses on-demand EC2 instances which may be more expensive but will not be interrupted
  onDemandCtxMiniwdl:
    requestSpotInstances: false
    engines:
      - type: wdl
        engine: miniwdl

  # The spot context uses EC2 spot instances which are usually cheaper but may be interrupted
  spotCtxMiniwdl:
    requestSpotInstances: true
    engines:
      - type: wdl
        engine: miniwdl

```

**Other information**

[//]: #  (detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, slack, etc)
