### ISSUE TITLE
Add support for specifying CPU for Snakemake head job

### ISSUE THREAD

**Issue by KevinSayers** [aws/amazon-genomics-cli#544]
[//]: #  (Before raising the feature request, please check to see if an existing feature request already exists.)

**Description**

The Snakemake head job currently runs on Fargate with `1 vcpu`. It would be useful to be able to specify additional resources for the head job. In particular, when Snakemake creates the Conda environment it can be quite slow with limited resources. 

**Use Case**

Execution of workflows that require the head job to utilize additional resources such as with Conda environments. 

**Proposed Solution**

Provide a way to specify the resource requirements. 
```
contexts:
  onDemandCtx: 
    headJobCPU: 4 #Or something along these lines. 
    engines:
      - type: snakemake
        engine: snakemake

```

**Other information**

[//]: #  (detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, slack, etc)
