### ISSUE TITLE
Quantify cost of using EFS provisioned throughput

### ISSUE THREAD

**Issue by wleepang** [aws/amazon-genomics-cli#590]
The following configuration:

```
filesystem:
  fsType: EFS
  configuration:
    provisionedThroughput: 1024
```

https://aws.github.io/amazon-genomics-cli/docs/workflow-engines/filesystems/efs/#provisioned-iops

Would create an EFS filesystem with 1024 MiB/s provisioned throughput. Based on the AWS Calculator, this would result in costs near $7K / mo.

Recommend reducing the suggested throughput value to at most 100 MiB/s as this is similar to throughput when burst credits are available for 1 TiB of storage. Also be clear that even this lower value has a cost estimate of $660 / mo.
